import "./globals.css";
import localFont from "next/font/local";

// Components
import Navbar from "@/components/modules/navbar/Navbar";

const IranSans = localFont({
  src: "./fonts/IRANSans.ttf",
});


export const metadata = {
  title: "Hamcar | همکار",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      dir="rtl"
        className={`${IranSans.className} antialiased`}
        >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
